<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="css/css.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
  </head>
<body>
         
    <center>
    <!-- inicio de la pagina --> 

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container-fluid bg-primary">
              <a class="navbar-brand" href="index.PHP"><img src="imagenes/logo.png" alt="mapeo de imagen" height="110" width="220"></a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="index.PHP">Inicio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="mision.html">Mision</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="vision.html">Vision</a>
                  </li>
                  <li><a class="nav-link active" aria-current="page" href="servicios.html">Catalogo</a>                  
                </ul>
                <form class="d-flex">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
<!-- inicio del cuerpo --> 
<!--inicio carrucel-->
<main>
  <div id="myCarousel" class="carousel slide" data-bs-ride="carousel">
    <ol class="carousel-indicators">
      <li data-bs-target="#myCarousel" data-bs-slide-to="0" class="active"></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="1"></li>
      <li data-bs-target="#myCarousel" data-bs-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="container">
        <img src="imagenes/autos4.jpg" alt="..." width="1000" heigth="675">
          <div class="carousel-caption text-start">
            <h1>...   ?</h1>
            <p>precio, confiablidad, rendimiento, mantenimiento, kilometraje, desgaste y el porcentaje de depreciación, siendo los temas más importantes a destacar, previo a la toma de decisión.</p>
            <p><a class="btn btn-lg btn-primary" href="servicios.html" role="button">Visita el Catalogo</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="container">
        <img src="imagenes/autos2.jpg" alt="..." width="1000" heigth="675">
          <div class="carousel-caption">
            <h1>Tesla Model 3</h1>
            <p>con un rating de cinco estrellas y aprobaciones de 96% para la seguridad del conductor, 86% para el asiento de niños, 74% de vulnerabilidad para peatones y 94% de asistencia segura.</p>
            <p><a class="btn btn-lg btn-primary" href="7.html" role="button">Ver mas...</a></p>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="container">
        <img src="imagenes/autos3.jfif" alt="..." width="1000" heigth="675">
          <div class="carousel-caption text-end">
            <h1>KIA SOUL 2021 Only you know why</h1>
            <p>Redescubre la emoción y atrévete a manejar la Nueva KIA Soul. Estimula tus sentidos y descubre por qué no querrás bajarte de ella.</p>
            <p><a class="btn btn-lg btn-primary" href="#" role="button">Ver mas...</a></p>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#myCarousel" role="button" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </a>
    <a class="carousel-control-next" href="#myCarousel" role="button" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </a>
  </div>
</main>
<!--final carrucel-->

<!-- START THE FEATURETTES -->

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">Evolución del sedán.<span class="text-muted"></span></h2>
    <p class="lead">El nuevo K5 hará que vuelvas a enamorarte de la conducción. Con su cabina orientada al conductor, tecnología avanzada, motores turboalimentados, suspensión de vía ancha que mejora la estabilidad, hasta 311 lb.-ft. par motor, opciones de conducción para todo clima y una plataforma completamente nueva, este sedán deportivo de tamaño mediano transformará por completo su experiencia de conducción este otoño </p>
  </div>
  <div class="col-md-5">
  <img src="imagenes/autos5.jpg" alt="..." width="500" heigth="675">

  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7 order-md-2">
    <h2 class="featurette-heading">2020 Model X.<span class="text-muted">Model X Long Range Plus</span></h2>
    <p class="lead">Rines negro onyx de 22''</p>
    <p class="lead">Interior premium con blanco y negro y decoración de madera oscura de fresno</p>
    <p class="lead">Autopilot</p>
    <p class="lead">Interior de seis asientos</p>

  </div>
  <div class="col-md-5 order-md-1">
  <img src="imagenes/autos6.jpg" alt="..." width="500" heigth="675">

  </div>
</div>

<hr class="featurette-divider">

<div class="row featurette">
  <div class="col-md-7">
    <h2 class="featurette-heading">NUEVA CHEVROLET<span class="text-muted">SUBURBAN</span></h2>
    <p class="lead">La icónica Chevrolet Suburban lleva más de 85 años de recorrer un camino lleno de determinación y éxito. Esta nueva generación ofrece mayor espacio para los pasajeros, un motor más potente y lo último en tecnología.</p>
  </div>
  <div class="col-md-5">
  <img src="imagenes/autos7.jpg" alt="..." width="500" heigth="675">

  </div>
</div>

<hr class="featurette-divider">

<!-- /END THE FEATURETTES -->


<!-- pie de pagina -->
<footer class="page-footer font-small blue pt-4">


  <div class="container-fluid text-center text-md-left">


    <div class="row">


      <div class="col-md-6 mt-md-0 mt-3">


        <h5 class="text-uppercase">Descripcion</h5>
        <p>Somos una empresa en la cual no buscamos que compres un auto....Deseamos que cumplas un sueño... Y esperamos que asi sea y que sea el mejor</p>

      </div>


      <hr class="clearfix w-100 d-md-none pb-3">

      <div class="col-md-3 mb-md-0 mb-3">

        <ul class="list-unstyled">
          <li>
            <a href="https://www.facebook.com/"><button><img src="imagenes/facebook.jpg" alt=" " width="20" heigth="20"></button></a>
          </li>
          <li>
            <a href="https://www.instagram.com/"><button><img src="imagenes/instagram.png" alt=" " width="20" heigth="20"></a>
          </li>
          </li>

</div>
      <div class="col-md-3 mb-md-0 mb-3">

        <ul class="list-unstyled">
          <li>
            <a href="https://twitter.com/home"><button><img src="imagenes/twitter.png" alt=" " width="20" heigth="20"></a>
          </li>
          <li>
            <a href="https://www.youtube.com/"><button><img src="imagenes/youtube.png" alt=" " width="20" heigth="20"></a>
          </li>
        </ul>

      </div>

    </div>

  </div>

  <div class="footer-copyright text-center py-3">© 2020 Copyright:Ricardo Antonio Peña Pedraza</a>
  </div>

</footer>     

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
</body>
</html>